POST http://localhost:3000/api/user/register HTTP/1.1
content-type: application/json

{    
   "name": "name2",
   "lastName": "lastName",
   "email":"name@email2.pl",
   "password":"password"
}
###
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmFtZTIiLCJsYXN0TmFtZSI6Imxhc3ROYW1lIiwiZW1haWwiOiJuYW1lQGVtYWlsMi5wbCIsInBhc3N3b3JkIjoiJDJiJDEwJGZSUTVldWlOUHgwVUVPY1ZhM0d3OWU0SHFNclhqRFpTNmgxdUdhLncvd3BaM1UzMEI5dDNtIiwiaWF0IjoxNzQ5Mjk4NTIyLCJleHAiOjE3NDkyOTg1ODJ9.P3I_lFbT5FWvXqFojTTg4T-OlgTcbFAe2QORyuVtNeI

###
POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{    
   "email":"name@email2.pl",
   "password":"password"
}

###eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwiaWF0IjoxNzQ5MjEyODkxLCJleHAiOjE3NDkyMTY0OTF9.EIFWgMzc2nMyRsjapmEszdq1eU52-qkNvpzpkcUn9to
GET  http://localhost:3000/api/profile/self
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwiaWF0IjoxNzQ5MzA4OTA3LCJleHAiOjE3NDkzMTI1MDd9.v62dY5LFYxbAlzoZEE7OmfjWEpK4Wcy0M2S6vi3ObME

###
PATCH  http://localhost:3000/api/profile HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwiaWF0IjoxNzQ5MzA4OTA3LCJleHAiOjE3NDkzMTI1MDd9.v62dY5LFYxbAlzoZEE7OmfjWEpK4Wcy0M2S6vi3ObME

{    
   "name":"test",
   "lastName":"Filip2"
}