GET http://localhost:3000/api/tags HTTP/1.1

###

POST http://localhost:3000/api/tags HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwiaWF0IjoxNzQ5MjEwOTkzLCJleHAiOjE3NDkyMTQ1OTN9.uMF9eNnBdpk5TYmlQFCBbK_qC3EO2N9Ucfkjma5Ue48

{
    "tag":"#lol112"
}

####

PATCH http://localhost:3000/api/photos/tags
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwiaWF0IjoxNzQ5MjEwOTkzLCJleHAiOjE3NDkyMTQ1OTN9.uMF9eNnBdpk5TYmlQFCBbK_qC3EO2N9Ucfkjma5Ue48


{
    "imageId":100,
    "tagId":2
}

###

PATCH http://localhost:3000/api/photos/tags/mass
content-type: application/json

{
    "imageId":100,
    "tagsId":[0,3,6]
}

###get all 
GET http://localhost:3000/api/photos/tags/100 HTTP/1.1

###
GET http://localhost:3000/api/filters/metadata/17471223618839

###
PATCH http://localhost:3000/api/filters

{
    "id":100,
    "filterName":"test"
}

### w przegldarce to wkleic
http://localhost:3000/api/getimage/1747124054447

###
GET http://localhost:3000/api/getimage/1747727091299/filter/flop